evolution:
  enabled: true
  evaluation_interval: 604800
hosts:
  primary:
    config_file: config.yaml
    priority: high
knowledge_integration:
  interval: 3600
  threshold: 0.75
log_level: INFO
monolith_data_dir: monolith_data
